train: /dataset/OCR_data/images/train
val: /dataset/OCR_data/images/val
test:  # test images (optional)

# Classes
nc: 30
names: ['1', '2', '3', '4', '5', '6', '7', '8', '9', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'K', 'L', 'M', 'N', 'P', 'S', 'T', 'U', 'V', 'X', 'Y', 'Z', '0']